accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include, path, reverse_lazy
from accounts.views import signup

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
]

receipts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include, path, reverse_lazy
from receipts.views import (
    CreateAccountView,
    CreateExpenseCategoryView,
    ReceiptListView,
    CreateReceiptView,
    AccountListView,
    ExpenseCategoryListView,
)

urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", CreateReceiptView.as_view(), name="receipt_new"),
    path("accounts/create/", CreateAccountView.as_view(), name="account_new"),
    path(
        "categories/create/",
        CreateExpenseCategoryView.as_view(),
        name="expense_category_new",
    ),
    path("accounts/", AccountListView.as_view(), name="accounts_list"),
    path(
        "categories/",
        ExpenseCategoryListView.as_view(),
        name="expense_category_list",
    ),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from tkinter import CASCADE
from django.db import models
from django.conf import settings
from django.forms import CharField

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.
class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL, related_name="categories", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL, related_name="accounts", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateField()
    purchaser = models.ForeignKey(
        USER_MODEL, related_name="receipts", on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        "ExpenseCategory", related_name="receipts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        "Account", related_name="receipts", on_delete=models.CASCADE, null=True
    )

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect


# Create your views here.
def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    return render(request, "registration/signup.html", {"form": form})

receipts/views.py
from attr import fields
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from receipts.models import Receipt, Account, ExpenseCategory
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import redirect
from django.views.generic.list import ListView


# Create your views here.


class ReceiptListView(ListView, LoginRequiredMixin):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return Receipt.objects.filter(purchaser=self.request.user)


class AccountListView(ListView, LoginRequiredMixin):
    model = Account
    template_name = "accounts/list.html"

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return Account.objects.filter(owner=self.request.user)


class ExpenseCategoryListView(ListView, LoginRequiredMixin):
    model = ExpenseCategory
    template_name = "categories/list.html"

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return ExpenseCategory.objects.filter(owner=self.request.user)


class CreateAccountView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "accounts/new.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        account = form.save(commit=False)
        account.owner = self.request.user
        account.save()
        form.save_m2m()
        return redirect("home")


class CreateExpenseCategoryView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "categories/new.html"
    fields = ["name"]

    def form_valid(self, form):
        expenseCategory = form.save(commit=False)
        expenseCategory.owner = self.request.user
        expenseCategory.save()
        form.save_m2m()
        return redirect("home")


class CreateReceiptView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/new.html"
    fields = ["vendor", "total", "tax", "date", "account", "category"]
    success_url = reverse_lazy("receipts_list")

    def form_valid(self, form):
        receipt = form.save(commit=False)
        receipt.purchaser = self.request.user
        receipt.save()
        form.save_m2m()
        return redirect("home")

accounts/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Receipts</title>
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>

<body>
  <header>
    <nav>
      <ul>
        <li>
          <a href="{% url 'home' %}">Home</a>
        </li>
        {% if user.is_staff %}
        <li>
          <a href="{% url 'admin:index' %}">Admin</a>
        </li>
        {% endif %}

        {% if user.is_authenticated %}
        <li>
          <a href="{% url 'logout' %}">Logout</a>
        </li>

        {% else %}
        <li>
          <a href="{% url 'login' %}">Login</a>
        </li>
        <li>
          <a href="{% url 'signup' %}">Sign up</a>
        </li>
        {% endif %}
        <li>
          <a href="{% url 'account_new' %}">Create Account</a>
        </li>
        <li>
          <a href="{% url 'expense_category_new' %}">Create Expense Category</a>
        </li>
        <li>
          <a href="{% url 'receipt_new' %}">Create Receipt</a>
        </li>
      </ul>
    </nav>
  </header>
  {% block content %}

  {% endblock content %}
</body>

</html>

receipts/templates/accounts/list.html
{% extends 'base.html' %}

{% block content %}
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Account Number</th>
      <th>Number of Receipts</th>
    </tr>
  </thead>
  <tbody>
    {% for account in account_list %}
    <tr>
      <td>{{ account.name }}</td>
      <td>{{ account.number }}</td>
      <td>{{ account.receipts.all|length }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

receipts/templates/accounts/new.html
{% extends 'base.html' %}

{% block content %}
<main>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="control">
      <button class="button">Create</button>
    </div>
  </form>
</main>
{% endblock content %}

receipts/templates/categories/list.html
{% extends 'base.html' %}

{% block content %}
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number of Receipts</th>
    </tr>
  </thead>
  <tbody>
    {% for category in expensecategory_list %}
    <tr>
      <td>{{ category.name }}</td>
      <td>{{ category.receipts.all|length }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

receipts/templates/categories/new.html
{% extends 'base.html' %}

{% block content %}
<main>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="control">
      <button class="button">Create</button>
    </div>
  </form>
</main>
{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %}

{% load decoder %}

{% block content %}
<main class="link-grid">
  <div class="link-grid-entry">
    <a href="{% url 'accounts_list' %}">Accounts List View</a>
  </div>
  <div class="link-grid-entry">
    <a href="{% url 'expense_category_list' %}">Expense Category List View</a>
  </div>

  {% if user.is_authenticated %}
  <table>
    <thead>
      <tr>
        <th>Vendor</th>
        <th>Total</th>
        <th>Tax</th>
        <th>Date</th>
        <th>Category</th>
        <th>Account</th>
      </tr>
    </thead>
    <tbody>
      {% for receipt in receipt_list %}
      <tr>
        <td>{{ receipt.vendor }}</td>
        <td>{{ receipt.total }}</td>
        <td>{{ receipt.tax }}</td>
        <td>{{ receipt.date }}</td>
        <td>{{ receipt.category }}</td>
        <td>{{ receipt.account | default_if_none:"Cash" }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% endif %}

  <!-- <div>
    <p> Special Decoder </p>
    <form method="post">
      <input placeholder="enter hex message" required type="string" name="hex">
      {% csrf_token %}
      <button class="button">Decode</button>
    </form>
    <p>Decoded message: </p>
  </div> -->
</main>

{% endblock content %}

receipts/templates/receipts/new.html
{% extends 'base.html' %}

{% block content %}
<main>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="control">
      <button class="button">Create</button>
    </div>
  </form>
</main>
{% endblock content %}